name: C/C++ CI

on:
  push:
    branches: [ "main", "test", "1.0" ]
  pull_request:
    branches: [ "main", "test", "1.0" ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: autoreconf
        run: autoreconf --install
      - name: configure
        run: ./configure
      - name: make
        run: make
      - name: make check
        run: make check
      - name: upload logs
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: librtpi_test_logs
          path: tests/**/*.log
